# Generated by Django 5.2.7 on 2025-10-27 01:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_businessregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessregistration',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='businessregistration',
            name='business_type',
            field=models.CharField(choices=[('bakery', 'Bakery'), ('cafe', 'Cafe'), ('grocery', 'Grocery / Market'), ('caterer', 'Caterer'), ('food_truck', 'Food Truck'), ('restaurant', 'Restaurant'), ('other', 'Other')], max_length=20),
        ),
    ]
