# Generated by Django 5.2.7 on 2025-11-04 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_businessregistration_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessregistration',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
