# Generated by Django 5.2.8 on 2025-11-18 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_businessregistration_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessregistration',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='business_logos/'),
        ),
    ]
