# Generated by Django 5.2.8 on 2025-11-07 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_update_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
    ]
