# Generated by Django 5.2.8 on 2025-11-07 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_rename_business_pr_status_abc123_idx_business_pr_status_daf8d6_idx_and_more'),
        ('market', '0003_remove_cartitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.product'),
        ),
    ]
