# Generated by Django 5.2.8 on 2025-11-13 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_alter_order_options_order_payment_intent_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='bag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='market.bag'),
        ),
    ]
