# Generated by Django 5.2.7 on 2025-11-04 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_alter_listing_options_listing_address_listing_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='min_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum price for dynamic pricing', max_digits=8, null=True),
        ),
    ]