# Generated by Django 5.2.7 on 2025-11-04 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_listing_min_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='end_time',
            field=models.DateTimeField(blank=True, help_text='End time for dynamic pricing', null=True),
        ),
    ]