# Generated by Django 5.2.7 on 2025-11-06 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_listing_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='end_time',
            field=models.DateTimeField(blank=True, help_text='End time for dynamic pricing.', null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='min_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum bid price for barter bids', max_digits=8, null=True),
        ),
    ]
