# Generated by Django 5.2.8 on 2025-11-07 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_product'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='product',
            new_name='business_pr_status_daf8d6_idx',
            old_name='business_pr_status_abc123_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='business_pr_owner_i_4450ff_idx',
            old_name='business_pr_owner_i_abc123_idx',
        ),
        migrations.AlterField(
            model_name='listing',
            name='end_time',
            field=models.DateTimeField(blank=True, help_text='End time for dynamic pricing.', null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='min_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum bid price for barter bids', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='base_price',
            field=models.DecimalField(decimal_places=2, help_text='The initial price when the product becomes available', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='end_time',
            field=models.DateTimeField(blank=True, help_text='End time for dynamic discounts', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum price for dynamic pricing. Floor price for bids.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes about the product.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pickup_by',
            field=models.DateTimeField(blank=True, help_text='Deadline for pickup for dynamic pricing', null=True),
        ),
    ]
