# Generated by Django 5.2.8 on 2025-11-09 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_rename_business_pr_status_abc123_idx_business_pr_status_daf8d6_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='business_pr_status_daf8d6_idx',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pickup_by',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pricing_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ready_after',
        ),
    ]
