# Generated by Django 5.2.7 on 2025-11-10 06:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_merge_0005_alter_and_0007_remove'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Bid amount', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='business.product')),
            ],
            options={
                'ordering': ['-amount', '-created_at'],
                'indexes': [models.Index(fields=['product', '-amount'], name='business_bi_product_4d1c84_idx'), models.Index(fields=['bidder'], name='business_bi_bidder__e07e1b_idx')],
            },
        ),
    ]
