# Generated by Django 5.2.7 on 2025-11-11 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='enable_bidding',
            field=models.BooleanField(default=False, help_text='Enable bidding/bartering for this product'),
        ),
    ]
