# Generated by Django 5.2.7 on 2025-11-11 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0010_product_enable_bidding'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='winning_bid',
            field=models.OneToOneField(blank=True, help_text='The winning bid for this product (set when bidding ends)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winning_product', to='business.bid'),
        ),
    ]
